#
# Executes commands at login pre-zshrc.

# Browser
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Editors
export DEFAULT_USER="sublime"
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export TERMINAL="xterm"
export TERM="xterm-256color"
export EDITOR="nvim"
export BROWSER="chromium"
export NODE_OPTIONS=--max_old_space_size=4096

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Paths
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export PATH=${PATH}:${HOME}/git/scripts/
export PATH=${PATH}:${HOME}/git/scripts/bash
export PATH=${PATH}:${HOME}/git/scripts/python
export PATH=${PATH}:${HOME}/git/scripts/node/dist
export PATH=${PATH}:${HOME}/.local/bin
export PATH=~/.npm-global/bin:$PATH

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Auto login on tty1
if systemctl -q is-active graphical.target && [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx
fi
