# Change xterm cursor into ibeam
echo -e -n "\x1b[\x35 q"

export PATH=/srv/scripts:$PATH

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


ENABLE_CORRECTION="true"

# ---------- Aliases ----------

# Pacman
alias pac="sudo pacman -S"
alias pacu="sudo pacman -Syyu"
alias pacs="sudo pacman -Ss"
alias pacr="sudo pacman -Rs"

alias aur="yay -S"
alias auru="yay -Syyu"
alias aurs="yay -Ss"
alias aurr="yay -Rs"

# Services
alias start="sudo systemctl start"
alias restart="sudo systemctl restart"
alias status="sudo systemctl status"
alias stop="sudo systemctl stop"
alias disable="sudo systemctl disable"
alias enable="sudo systemctl enable"

# File Management
alias copy="rsync -Phva --info=progress2"
alias fsizes="du -hsc *"

# System
# Shortcuts
alias wifi="sudo wicd-curses"

alias mount-server="sudo sshfs -o allow_other sublime@10.0.0.25:/ /mnt/ichigo"
alias mount-seedbox="sudo sshfs -o allow_other callmekory@gegenees.feralhosting.com:/media/sdaj1/callmekory /mnt/seedbox/"

alias wake-server="wol d4:ae:52:d3:c3:62"

bindkey -v

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
