# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Change xterm cursor into ibeam
echo -e -n "\x1b[\x35 q"
EDITOR="nvim"
export PATH=/srv/scripts:$PATH
export "MICRO_TRUECOLOR=1"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


ENABLE_CORRECTION="true"

ZSH_THEME="powerlevel10k/powerlevel10k"

# ---------- Aliases ----------

# tmux
alias ta="tmux attach-session -t"
alias tk="tmux kill-session"
alias tl="tmux list-sessions"
alias tn="tmux new-session -s"
alias tr="tmux rename-session"

# Pacman
alias pac="sudo pacman -S"
alias pacu="sudo pacman -Syyu"
alias pacs="sudo pacman -Ss"
alias pacr="sudo pacman -Rs"

alias aur="yay -S"
alias auru="yay -Syyu"
alias aurs="yay -Ss"
alias aurr="yay -Rs"

# Services
alias start="sudo systemctl start"
alias restart="sudo systemctl restart"
alias status="sudo systemctl status"
alias stop="sudo systemctl stop"
alias disable="sudo systemctl disable"
alias enable="sudo systemctl enable"

# File Management
alias copy="rsync -Phva --info=progress2"
alias fsizes="du -hsc *"
alias rm="trash-put"
alias disk-speedtest="dd if=/dev/zero of=./10GB.file bs=1M count=10240 oflag=nocache conv=fdatasync status=progress"

# System
# Shortcuts
alias v="nvim"
alias wifi="sudo wicd-curses"
alias wake-server="wol d4:ae:52:d3:c3:62"

bindkey -v

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#-hostname-color
#02-sysinfo
#/srv/scripts/motd/35-diskspace
#/srv/scripts/motd/60-docker
#source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
